# Generated by Django 6.0.3 on 2026-06-27 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Add all new fields first
        migrations.AddField(
            model_name='wishlist',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='model_type',
            field=models.CharField(
                choices=[
                    ('product', 'Product'), ('men', 'Men'), ('women', 'Women'),
                    ('kids', 'Kids'), ('kids_tshirts', 'Kids T-Shirts'),
                    ('kids_suits', 'Kids Suits'), ('kids_dress', 'Kids Dress'),
                    ('kids_jeans', 'Kids Jeans'),
                ],
                default='product',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.FloatField(default=0),
        ),
        # 2. Remove old unique_together that references 'product'
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        # 3. Remove old FK field
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        # 4. Now set the new unique_together using the new fields
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'model_type', 'object_id')},
        ),
    ]
