# Generated by Django 6.0.3 on 2026-07-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_wishlist_unique_together_wishlist_image_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kids',
        ),
        migrations.DeleteModel(
            name='Kids_dress',
        ),
        migrations.DeleteModel(
            name='Kids_jeans',
        ),
        migrations.DeleteModel(
            name='Kids_suits',
        ),
        migrations.DeleteModel(
            name='Kids_tshirts',
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='model_type',
            field=models.CharField(choices=[('product', 'Product'), ('men', 'Men'), ('women', 'Women')], default='product', max_length=20),
        ),
    ]
