# Generated by Django 6.0.3 on 2026-07-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_delete_kids_delete_kids_dress_delete_kids_jeans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='discount',
            field=models.FloatField(default=0, help_text='Discount percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0, help_text='Discount percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='women',
            name='discount',
            field=models.FloatField(default=0, help_text='Discount percentage (0-100)'),
        ),
    ]
