# Generated by Django 6.0.3 on 2026-07-20 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_contact_admin_review_contact_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admindiscussion',
            name='discussion_type',
            field=models.CharField(choices=[('group', 'Group (All Sub-Admins)'), ('individual', 'Individual Sub-Admin')], default='group', max_length=20),
        ),
        migrations.AddField(
            model_name='admindiscussion',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Specific Sub-Admin if individual chat; null if Group', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_discussions', to=settings.AUTH_USER_MODEL),
        ),
    ]
