# Generated by Django 6.0.5 on 2026-07-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_alter_book_email_alter_registration_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
