# Generated by Django 6.0.5 on 2026-07-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAdminRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('store_name', models.CharField(max_length=100)),
                ('reason', models.TextField(help_text='Reason / Business details for applying as seller')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved (Credentials Sent)'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
