# Generated by Django 6.0.3 on 2026-07-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_subadminrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='stock',
            field=models.IntegerField(default=25, help_text='Stock quantity available'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_partner',
            field=models.CharField(blank=True, default='STYLEVERSE Express', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=25, help_text='Stock quantity available'),
        ),
        migrations.AddField(
            model_name='subadminrequest',
            name='requested_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='women',
            name='stock',
            field=models.IntegerField(default=25, help_text='Stock quantity available'),
        ),
    ]
