# Generated by Django 6.0.3 on 2026-07-25 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0016_men_stock_order_courier_partner_order_delivery_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Sub-Admin who added this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_men_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Sub-Admin who added this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_general_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='women',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Sub-Admin who added this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_women_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
