# Generated by Django 6.0.3 on 2026-08-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0017_men_created_by_product_created_by_women_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-truck', help_text='FontAwesome icon class e.g. fa-truck, fa-rotate-left, fa-shield-halved, fa-headset, fa-tag, fa-star', max_length=50)),
                ('text', models.CharField(help_text='Announcement line text shown in scrolling ticker', max_length=255)),
                ('link_url', models.CharField(blank=True, default='', help_text='Optional URL link when clicked', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Show in scrolling news ticker line')),
                ('order', models.IntegerField(default=0, help_text='Sort order priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
