# Generated by Django 6.0.3 on 2026-08-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0018_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='product_code',
            field=models.CharField(blank=True, default='', help_text='Unique Product ID / SKU', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='OrderItem'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, default='', help_text='Unique Product ID / SKU', max_length=50),
        ),
        migrations.AddField(
            model_name='women',
            name='product_code',
            field=models.CharField(blank=True, default='', help_text='Unique Product ID / SKU', max_length=50),
        ),
    ]
