# Generated by Django 6.0.3 on 2026-08-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0020_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='brand',
            field=models.CharField(blank=True, default='STYLEVERSE', help_text="Brand name e.g. Zara, Nike, Levi's, Gucci, Puma, STYLEVERSE", max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='STYLEVERSE', help_text="Brand name e.g. Zara, Nike, Levi's, Gucci, Puma, STYLEVERSE", max_length=50),
        ),
        migrations.AddField(
            model_name='productrequest',
            name='brand',
            field=models.CharField(blank=True, default='STYLEVERSE', help_text="Brand name e.g. Zara, Nike, Levi's, Gucci, Puma, STYLEVERSE", max_length=50),
        ),
        migrations.AddField(
            model_name='women',
            name='brand',
            field=models.CharField(blank=True, default='STYLEVERSE', help_text="Brand name e.g. Zara, Nike, Levi's, Gucci, Puma, STYLEVERSE", max_length=50),
        ),
    ]
